#!/bin/bash

qqvolume_default_master="Master"
qqvolume_default_card="2"
qqvolume_default_device="0"
qqvolume_default_hw="hw:$qqvolume_default_card,$qqvolume_default_device"
qqvolume_ext_master="IEC958"
qqvolume_ext_card="1"
qqvolume_ext_device="3"
qqvolume_ext_hw="hw:$qqvolume_ext_card,$qqvolume_ext_device"

qqrecord_mic_audio="$qqvolume_default_hw"

qqscreen_int_monitor="eDP"
qqscreen_int_res="2560x1440"
qqscreen_int_rate="165.00"
qqscreen_ext_monitor="HDMI-A-0"
qqscreen_ext_res="2560x1440"
qqscreen_ext_rate="144.00"
qqscreen_parents_monitor="???"
qqscreen_parents_res="???"

qqbacklight_int_path="/sys/class/backlight/amdgpu_bl0"
qqbacklight_int_increment="20"
qqbacklight_key_path="/sys/class/leds/asus::kbd_backlight"
qqbacklight_key_increment="1"
qqbacklight_ext_device="/dev/i2c-6"
qqbacklight_ext_address="0x10"
qqbacklight_ext_increment="34"

qqdevice_mice=("Logitech M325" "Logitech G400s")
qqdevice_trackpads=("ASUE1209:00 04F3:319F Touchpad")
qqdevice_trackpoints=()
qqdevice_keyboards=("Asus Keyboard")
