#!/bin/bash

qqvolume_default_master="Master"
qqvolume_default_card="1"
qqvolume_default_device="0"
qqvolume_default_hw="hw:$qqvolume_default_card,$qqvolume_default_device"
qqvolume_ext_master="IEC958"
qqvolume_ext_card="0"
qqvolume_ext_device="7"
qqvolume_ext_hw="hw:$qqvolume_ext_card,$qqvolume_ext_device"

qqrecord_mic_audio="$qqvolume_default_hw"

qqscreen_int_monitor="eDP-1"
qqscreen_int_res="2560x1600"
qqscreen_int_rate="59.97"
qqscreen_ext_monitor="DP-2"
qqscreen_ext_res="2560x1440"
qqscreen_ext_rate="120.00"
qqscreen_parents_monitor="HDMI-2"
qqscreen_parents_res="1920x1080"

qqbacklight_int_path="/sys/class/backlight/intel_backlight"
qqbacklight_int_increment="150"
qqbacklight_key_path="/sys/class/leds/smc::kbd_backlight"
qqbacklight_key_increment="50"
qqbacklight_ext_device="/dev/i2c-7"
qqbacklight_ext_address="0x10"
qqbacklight_ext_increment="34"

qqpc_backlight_key_path="$qqbacklight_key_path"

qqdevice_mice=("Logitech M325" "Logitech G400s")
qqdevice_trackpads=("bcm5974")
qqdevice_trackpoints=()
qqdevice_keyboards=("Apple Inc. Apple Internal Keyboard / Trackpad")
