#!/bin/bash

qqdefault_master="Master"
qqdefault_card="0"
qqdefault_device="0"
qqdefault_hw="hw:$qqdefault_card,$qqdefault_device"
qqext_master="IEC958"
qqext_card="0"
qqext_device="3"
qqext_hw="hw:$qqext_card,$qqext_device"

qqmic_audio="$qqdefault_hw"

qqinternal_monitor="LVDS-1"
qqinternal_res="1920x1080"
qqinternal_rate="60.00"
qqexternal_monitor="DP-1"
qqexternal_res="2560x1440"
qqexternal_rate="75.00"
qqparents_monitor="HDMI-1"
qqparents_res="1920x1080"

qqinternal_backlight_path="/sys/class/backlight/acpi_video0"
qqinternal_increment="1"
qqkeyboard_backlight_path="/sys/class/leds/tpacpi::thinklight"
qqkeyboard_increment="255"
qqexternal_backlight_device="/dev/i2c-7"
qqexternal_backlight_address="0x10"
qqexternal_increment="34"

qqmice=("Logitech M325" "Logitech G400s")
qqtrackpads=("SynPS/2 Synaptics TouchPad")
qqtrackpoints=("TPPS/2 IBM TrackPoint")
