#!/bin/sh

# ---------------------------
# BASIC CONFIG
# ---------------------------
bspc config border_width 10
bspc config window_gap 0
bspc config split_ratio 0.5

# set border colors
bspc config normal_border_color "#202020"
bspc config focused_border_color "#909090"
bspc config active_border_color "#202020"
bspc config presel_feedback_color "#909090"

# set window management controls
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

# pointer controls
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

# fix padding when restarting
bspc config right_padding 0
bspc config left_padding 0
bspc config top_padding 0
height=$(grep height "$HOME"/.config/polybar/config.ini | awk '{print $3}' | sed 's/pt//')
dpi=$(grep dpi "$HOME"/.Xresources | awk '{print $2}')
height_in_pixels=$(echo "$height * ($dpi / 72)" | bc -l | xargs printf "%.0f")
bspc config bottom_padding "$height_in_pixels"

# ---------------------------
# STARTUP
# ---------------------------
# if running bspwm for the first time in login
if [ ! -f /tmp/bspwm_first_run ]; then
	bspc monitor -d 1 2 3 4
	~/.local/userscripts/bin/qqvolume -input -off
	~/.local/userscripts/bin/qqdevice -trackpad -stop
	xautolock -time 5 -detectsleep -locker "$HOME/.local/userscripts/bin/qqpc -lock -notwithaudio > /dev/null" &

	touch /tmp/bspwm_first_run
fi

# set keybindings
if pgrep -x sxhkd > /dev/null; then
	pkill -x sxhkd
fi
sxhkd &

# set polybar (on multiple monitors)
if pgrep -x polybar > /dev/null; then
	pkill -x polybar
fi
for monitor in $(polybar --list-monitors | cut -d":" -f1); do
	MONITOR=$monitor polybar &
done

# set compositor
if pgrep -x picom > /dev/null; then
	pkill -x picom
fi
picom &

# set desktop background
feh --bg-fill --random ~/bg.jpg &

# hide mouse after certain time
if pgrep -x unclutter > /dev/null; then
	pkill -x unclutter
fi
unclutter -idle 10 &

# disable screen blanking
xset dpms 0 0 0 && xset s 0 0 &

# set key repeat delay and speed
xset r rate 400 60 &

# set capslock key to esc
setxkbmap -option caps:escape_shifted_capslock &&
# set menu key to super_r
xmodmap -e "keysym Menu = Super_R" &
